### ISSUE TITLE
样式问题

### ISSUE THREAD

**Issue by zbsguilai** [17px/hexo-theme-cosy#10]
pnpm dev:hexo
pnpm dev:ui
执行完后，执行
pnpm dev
样式还是乱的

**Comment by 17px** [comment]
> pnpm dev:hexo pnpm dev:ui 执行完后，执行 pnpm dev 样式还是乱的

试试重新启一下 pnpm dev:hexo，然后手动刷下页面？☺

**Comment by zbsguilai** [comment]
解决了，但是搜索报错
![image](https://github.com/17px/hexo-theme-cosy/assets/54394717/5d32489b-d15b-4ea8-8551-0480f4ed3a46)

**Comment by zbsguilai** [comment]
能不能个最终部署的流程，我最后部署出来，样式全是乱的，太痛苦了
pnpm build 打包没啥问题
<img width="306" alt="image" src="https://github.com/17px/hexo-theme-cosy/assets/54394717/9aef0a69-ac4c-493b-9d67-c9298e81aef4">
但是之后怎么做呢，在打包后的文件使用hexo g d，命令无效

**Comment by 17px** [comment]
> 能不能个最终部署的流程，我最后部署出来，样式全是乱的，太痛苦了 pnpm build 打包没啥问题 <img alt="image" width="306" src="https://private-user-images.githubusercontent.com/54394717/292950321-9aef0a69-ac4c-493b-9d67-c9298e81aef4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NDc2NTAsIm5iZiI6MTcwMzY0NzM1MCwicGF0aCI6Ii81NDM5NDcxNy8yOTI5NTAzMjEtOWFlZjBhNjktYWM0Yy00OTNiLTlkNjctYzkyOThlODFhZWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDAzMjIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1MzAyZWI2MTg4MGYyMzI4NTRhM2NiYzBiODJjNTNiZmEyNWZkNjQxNThmMzU4ZjA4ODlkMWUwNjA3MWJjNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ghzzVlVMkUDBTB3kt5qPr8rYOCnR2LvBu1mcTSQnTuE"> 但是之后怎么做呢，在打包后的文件使用hexo g d，命令无效

这个build文件夹，直接扔到hexo/theme文件夹下面，再配置下_config.yml字段，就可以生效了。为啥样式会乱，控制台报错是什么呢？

**Comment by zbsguilai** [comment]
解决了，放到了theme下面，再推送
最后还有个小问题，我配置的域名不管用，不知道为啥。nginx已重启且域名审核通过
<img width="396" alt="image" src="https://github.com/17px/hexo-theme-cosy/assets/54394717/9a075b4f-881c-4ccc-9bef-be4309802379">

**Comment by 17px** [comment]
> 解决了，放到了theme下面，再推送 最后还有个小问题，我配置的域名不管用，不知道为啥。nginx已重启且域名审核通过 <img alt="image" width="396" src="https://private-user-images.githubusercontent.com/54394717/292952021-9a075b4f-881c-4ccc-9bef-be4309802379.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NDkwNzUsIm5iZiI6MTcwMzY0ODc3NSwicGF0aCI6Ii81NDM5NDcxNy8yOTI5NTIwMjEtOWEwNzViNGYtODgxYy00Y2NjLTliZWYtYmU0MzA5ODAyMzc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDAzNDYxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4Yzk4YTljNjIwZTM0OWI1OTExODY3OGY1ZmIwMGZmMzFlNTNjOTA5MTIxNmI5NDAyYWNkMmQ4YWVhOGI0MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZbR0h5e-7EfwrXUoncS69pl2t27fSY3drzLsHm9uCO4">

可能原因挺多的，应该和主题开发没什么关系，不太好回答😊
