### ISSUE TITLE
网站无法访问

### ISSUE THREAD

**Issue by Huaguang-XinZhe** [17px/hexo-theme-cosy#12]
![image](https://github.com/17px/hexo-theme-cosy/assets/76586072/493fda3b-aee7-4b4d-8560-e2a01dfab900)

您的证书过期了吗？

**Comment by 17px** [comment]
是的，我迁移到新的网址，您可以访问：https://maxshader.com/



陈不渡
***@***.***







                       
Original Email
                       
                     

Sender:"沐风（Mufeng）"< ***@***.*** &gt;;

Sent Time:2024/3/14 17:05

To:"17px/hexo-theme-cosy"< ***@***.*** &gt;;

Cc recipient:"Subscribed"< ***@***.*** &gt;;

Subject:[17px/hexo-theme-cosy] 网站无法访问 (Issue #12)




 
image.png (view on web)
 
您的证书过期了吗？
