### ISSUE TITLE
能否拓展Twikoo评论？

### ISSUE THREAD

**Issue by miaopasixx** [17px/hexo-theme-cosy#13]
valine限制很多，能否拓展Twikoo评论？😀

**Comment by 17px** [comment]
是个好主意，我会尽快调研，谢谢你的建议和支持

**Comment by miaopasixx** [comment]
> 是个好主意，我会尽快调研，谢谢你的建议和支持

滴滴，友联专车已到站！快上车，精彩之旅即将启程！🚌✨
https://blog.mpsxx.top/links

**Comment by 17px** [comment]
v2.1.1已加入Twikoo评论，文档head中使用
```
---
use: twikoo
---
```
