### ISSUE TITLE
发现移动端在暗黑模式下点击导航项或进入文章会闪烁一下

### ISSUE THREAD

**Issue by Huaguang-XinZhe** [17px/hexo-theme-cosy#3]
可能是点击的时候加载浅色主题，然后很快又换成了暗色。

录屏：
https://github.com/17px/hexo-theme-cosy/assets/76586072/928790ca-9572-41f1-a12f-2a1c0f90400a

**Comment by 17px** [comment]
这确实是一个交互体验上的问题，我会在后续的版本当中解决，感谢宝贵的意见

**Comment by 17px** [comment]
> 可能是点击的时候加载浅色主题，然后很快又换成了暗色。
> 
> 录屏： https://github.com/17px/hexo-theme-cosy/assets/76586072/928790ca-9572-41f1-a12f-2a1c0f90400a

[v1.4.0](https://github.com/17px/hexo-theme-cosy/releases/tag/v1.4.0)版本已经优化

**Comment by zbsguilai** [comment]
> > 可能是点击的时候加载浅色主题，然后很快又换成了暗色。
> > 录屏： https://github.com/17px/hexo-theme-cosy/assets/76586072/928790ca-9572-41f1-a12f-2a1c0f90400a
> 
> [v1.4.0](https://github.com/17px/hexo-theme-cosy/releases/tag/v1.4.0)版本已经优化

点击侧边导航栏的按钮，闪一下后切换页面的问题还在呀，是不是没合并到主分支

**Comment by 17px** [comment]
> > > 可能是点击的时候加载浅色主题，然后很快又换成了暗色。
> > > 录屏： https://github.com/17px/hexo-theme-cosy/assets/76586072/928790ca-9572-41f1-a12f-2a1c0f90400a
> > 
> > 
> > [v1.4.0](https://github.com/17px/hexo-theme-cosy/releases/tag/v1.4.0)版本已经优化
> 
> 点击侧边导航栏的按钮，闪一下后切换页面的问题还在呀，是不是没合并到主分支

确实，你说的对，服务端渲染首屏闪白的问题并没解决，我试试想办法解决
