### ISSUE TITLE
如果移动端的代码块能全宽显示就好了，这样看着会舒服一点😄

### ISSUE THREAD

**Issue by Huaguang-XinZhe** [17px/hexo-theme-cosy#4]
![Screenshot_2023-11-15-00-12-31-85_e39d2c7de19156b0683cd93e8735f348.jpg](https://github.com/17px/hexo-theme-cosy/assets/76586072/4519aea6-09e6-40e1-982f-4f3db1131c28)

**Comment by 17px** [comment]
感谢您提出的建议关于移动端代码块的全宽显示，在某些情况下，全宽显示的代码块会提供更好的阅读体验，我会认真考虑您的建议，如果您有更多的想法或细节希望补充😁
