### ISSUE TITLE
是否cosy不支持R语言在代码块中的高亮显示，如果是的话希望作者大大能加入

### ISSUE THREAD

**Issue by Mercury-02** [17px/hexo-theme-cosy#9]
因为我的python代码和yaml代码都可以正常高亮，而唯独R语言没有，希望能加入R语言高亮

**Comment by 17px** [comment]
> 因为我的python代码和yaml代码都可以正常高亮，而唯独R语言没有，希望能加入R语言高亮

首先，我们对于您在使用时遇到的不便表示诚挚的歉意。目前，v.1.4.4 版本之前，主题未支持 R 语言的语法高亮功能。这一决定是基于对于保持项目构建体积的精简的考虑，以及目前 Prism 代码高亮集成默认支持的语言范围。

我深知这一功能对于您的重要性。请放心，支持 R 语言的语法高亮功能将在我们的后续版本中得到解决。感谢您的理解与耐心等待。

如有任何进一步的建议或需求，欢迎随时与我交流。

**Comment by 17px** [comment]
> 因为我的python代码和yaml代码都可以正常高亮，而唯独R语言没有，希望能加入R语言高亮
在markdown语法中，试试 ```r 声明， ```R 大写会导致高亮失效 😁

**Comment by Mercury-02** [comment]
谢谢你，问题解决了！🤭

________________________________
发件人: 17px ***@***.***>
发送时间: 2023年12月7日 16:48
收件人: 17px/hexo-theme-cosy ***@***.***>
抄送: Wang Jun ***@***.***>; Author ***@***.***>
主题: Re: [17px/hexo-theme-cosy] 是否cosy不支持R语言在代码块中的高亮显示，如果是的话希望作者大大能加入 (Issue #9)


因为我的python代码和yaml代码都可以正常高亮，而唯独R语言没有，希望能加入R语言高亮
在markdown语法中，试试 r 声明， R 大写会导致高亮失效 😁
